require 'bundler/setup'
require 'rack/cors'
require 'grape'
require 'grape_logging'
require 'json'
require 'rest-client'
require 'active_record'
require 'grape/activerecord'
require 'kaminari/grape'
require 'grape-swagger'
require 'grape-entity'
require 'google/apis/calendar_v3'
require 'googleauth'
require './config/settings'

Grape::ActiveRecord.configure_from_file! 'config/database.yml'
ActiveRecord::Base.default_timezone = :local
