source 'http://rubygems.nos.ncu.edu.tw'
gem 'json'
gem 'rack'
gem 'rack-cors'
gem 'rack-contrib'
gem 'rspec'
gem 'airborne'
gem 'grape'
gem 'grape-swagger', git: 'https://github.com/ruby-grape/grape-swagger.git'
gem 'grape-entity'
gem 'grape_logging', git: 'https://github.com/aserafin/grape_logging.git'
gem 'activerecord'
gem 'grape-activerecord'
gem 'mysql2'
gem 'sqlite3'
gem 'kaminari', :require => 'kaminari/grape'
gem 'rest-client'
gem 'google-api-client'
